'on':
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    resources:
      instance-type: C5
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: context.event.github.url
  BuildAndDeploy:
    resources:
      instance-type: P4000
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    uses: container@v1
    with:
      context: /inputs/repo
      dockerfile: /inputs/repo/Dockerfile
      build_args:
        - key: CUDA_VISIBLE_DEVICES
          value: 0
      ports:
        - 8000:8000
      command: flask run --host=0.0.0.0 --port=8000
      env:
        - key: FLASK_APP
          value: app.server:app
